mutation CreateUser @auth(level: USER) {
  user_insert(data: {
    createdAt_expr: "request.time",
    id_expr: "uuidV4()"
  })
}

query GetUser @auth(level: USER) {
  user(key: {id_expr: "auth.uid"}) {
    id
    createdAt
    displayName
    email
  }
}

mutation UpdateCategory($categoryId: UUID!, $name: String) @auth(level: USER) {
  category_update(key: {id: $categoryId}, data: {name: $name})
}

query ListServicesByCategory($categoryId: UUID!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  services(where: {categoryId: {eq: $categoryId}}) {
    id
    name
    issuer
  }
}